//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.1433.
// 
namespace PrototypMIS.Referenz_Kunden {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://149.201.44.80/V4YOU/service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerByName(string name) {
            object[] results = this.Invoke("getCustomerByName", new object[] {
                        name});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCustomerByName(string name, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCustomerByName", new object[] {
                        name}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetCustomerByName(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerByRef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerByRef(string Ref) {
            object[] results = this.Invoke("getCustomerByRef", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCustomerByRef(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCustomerByRef", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetCustomerByRef(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSalesPersonByRef", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSalesPersonByRef(string Ref) {
            object[] results = this.Invoke("getSalesPersonByRef", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSalesPersonByRef(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSalesPersonByRef", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetSalesPersonByRef(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsByCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsByCustomer(string Ref) {
            object[] results = this.Invoke("getAddsByCustomer", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsByCustomer(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsByCustomer", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsByCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getConstructionSites", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getConstructionSites(string Ref) {
            object[] results = this.Invoke("getConstructionSites", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetConstructionSites(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getConstructionSites", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetConstructionSites(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsHeadsByCustomer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsHeadsByCustomer(string Ref) {
            object[] results = this.Invoke("getAddsHeadsByCustomer", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsHeadsByCustomer(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsHeadsByCustomer", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsHeadsByCustomer(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsDetailsByHeadID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsDetailsByHeadID(string AUATNR) {
            object[] results = this.Invoke("getAddsDetailsByHeadID", new object[] {
                        AUATNR});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsDetailsByHeadID(string AUATNR, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsDetailsByHeadID", new object[] {
                        AUATNR}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsDetailsByHeadID(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsBySalesPerson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsBySalesPerson(string Ref) {
            object[] results = this.Invoke("getAddsBySalesPerson", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsBySalesPerson(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsBySalesPerson", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsBySalesPerson(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getSalesMeetingReports", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getSalesMeetingReports(string Ref) {
            object[] results = this.Invoke("getSalesMeetingReports", new object[] {
                        Ref});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetSalesMeetingReports(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getSalesMeetingReports", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetSalesMeetingReports(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsFormatsBonus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsFormatsBonus(string ObjRef) {
            object[] results = this.Invoke("getAddsFormatsBonus", new object[] {
                        ObjRef});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsFormatsBonus(string ObjRef, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsFormatsBonus", new object[] {
                        ObjRef}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsFormatsBonus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsObjects", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsObjects() {
            object[] results = this.Invoke("getAddsObjects", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsObjects(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsObjects", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsObjects(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsPageFormats", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getAddsPageFormats(string ObjRef) {
            object[] results = this.Invoke("getAddsPageFormats", new object[] {
                        ObjRef});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsPageFormats(string ObjRef, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsPageFormats", new object[] {
                        ObjRef}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetAddsPageFormats(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsFormatsPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float getAddsFormatsPrice(string VLOJNR, string FORUNR, string FOFONR) {
            object[] results = this.Invoke("getAddsFormatsPrice", new object[] {
                        VLOJNR,
                        FORUNR,
                        FOFONR});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsFormatsPrice(string VLOJNR, string FORUNR, string FOFONR, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsFormatsPrice", new object[] {
                        VLOJNR,
                        FORUNR,
                        FOFONR}, callback, asyncState);
        }
        
        /// <remarks/>
        public float EndgetAddsFormatsPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsFormatsBonusPrice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public float getAddsFormatsBonusPrice(string FOFONR) {
            object[] results = this.Invoke("getAddsFormatsBonusPrice", new object[] {
                        FOFONR});
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsFormatsBonusPrice(string FOFONR, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsFormatsBonusPrice", new object[] {
                        FOFONR}, callback, asyncState);
        }
        
        /// <remarks/>
        public float EndgetAddsFormatsBonusPrice(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((float)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getAddsStatistics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddsStatistics getAddsStatistics(string Ref) {
            object[] results = this.Invoke("getAddsStatistics", new object[] {
                        Ref});
            return ((AddsStatistics)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetAddsStatistics(string Ref, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getAddsStatistics", new object[] {
                        Ref}, callback, asyncState);
        }
        
        /// <remarks/>
        public AddsStatistics EndgetAddsStatistics(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddsStatistics)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCustomerStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getCustomerStatus(string KNDNR) {
            object[] results = this.Invoke("getCustomerStatus", new object[] {
                        KNDNR});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCustomerStatus(string KNDNR, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCustomerStatus", new object[] {
                        KNDNR}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndgetCustomerStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertCustomerStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertCustomerStatus(string KNDNR, string ABONR, string comment, string status) {
            object[] results = this.Invoke("InsertCustomerStatus", new object[] {
                        KNDNR,
                        ABONR,
                        comment,
                        status});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertCustomerStatus(string KNDNR, string ABONR, string comment, string status, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertCustomerStatus", new object[] {
                        KNDNR,
                        ABONR,
                        comment,
                        status}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertCustomerStatus(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/saveSalesMeetingReport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int saveSalesMeetingReport([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] report, string ERREFN) {
            object[] results = this.Invoke("saveSalesMeetingReport", new object[] {
                        report,
                        ERREFN});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsaveSalesMeetingReport(byte[] report, string ERREFN, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("saveSalesMeetingReport", new object[] {
                        report,
                        ERREFN}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndsaveSalesMeetingReport(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AddsStatistics {
        
        private int total_sales_numberField;
        
        private float total_sales_volField;
        
        /// <remarks/>
        public int total_sales_number {
            get {
                return this.total_sales_numberField;
            }
            set {
                this.total_sales_numberField = value;
            }
        }
        
        /// <remarks/>
        public float total_sales_vol {
            get {
                return this.total_sales_volField;
            }
            set {
                this.total_sales_volField = value;
            }
        }
    }
}
